import React, { useState } from 'react';
import { BackendContextType, Language, Voucher, formatCurrency } from '../../types';
import { TRANSLATIONS } from '../../services/translations';
import ConfirmModal from './ConfirmModal';
import {
  Ticket, Plus, Edit, Trash2, CheckCircle, XCircle, TrendingUp,
  BarChart2, Calendar, AlertCircle, Save, X, Tag
} from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend
} from 'recharts';

interface VoucherManagerProps {
  backend: BackendContextType;
  lang: Language;
}

const VoucherManager: React.FC<VoucherManagerProps> = ({ backend, lang }) => {
  const t = TRANSLATIONS[lang];
  const { state, addVoucher, updateVoucher, deleteVoucher } = backend;

  const [activeTab, setActiveTab] = useState<'list' | 'reports'>('list');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [deletingVoucherId, setDeletingVoucherId] = useState<string | null>(null);

  const [formData, setFormData] = useState<Omit<Voucher, 'id' | 'usedCount'>>({
    code: '',
    type: 'PERCENT',
    value: 0,
    minOrderValue: 0,
    maxDiscount: 0,
    startDate: new Date().toISOString().split('T')[0],
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    usageLimit: 100,
    status: 'ACTIVE'
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (editingId) {
      updateVoucher(editingId, formData);
    } else {
      addVoucher(formData);
    }
    setIsModalOpen(false);
    resetForm();
  };

  const resetForm = () => {
    setEditingId(null);
    setFormData({
        code: '',
        type: 'PERCENT',
        value: 0,
        minOrderValue: 0,
        maxDiscount: 0,
        startDate: new Date().toISOString().split('T')[0],
        endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        usageLimit: 100,
        status: 'ACTIVE'
    });
  };

    const openEdit = (v: Voucher) => {
        setEditingId(v.id);
        setFormData({
          code: v.code,
            type: v.type,
            value: v.value,
            minOrderValue: v.minOrderValue,
            maxDiscount: v.maxDiscount || 0,
            startDate: v.startDate.split('T')[0],
            endDate: v.endDate.split('T')[0],
            usageLimit: v.usageLimit,
            status: v.status
        });
        setIsModalOpen(true);
    };

  // --- Reports Logic ---
  // Calculate revenue generated by vouchers (orders where this voucher was used)
  const voucherStats = state.vouchers.map(v => {
      const ordersWithVoucher = state.orders.filter(o => o.voucherCode === v.code && o.status !== 'CANCELLED');
      const revenue = ordersWithVoucher.reduce((sum, o) => sum + o.total, 0); // Total after discount
      const totalDiscount = ordersWithVoucher.reduce((sum, o) => sum + (o.voucherDiscount || 0), 0);

      return {
          code: v.code,
          usage: v.usedCount,
          revenue,
          discount: totalDiscount,
          roi: totalDiscount > 0 ? (revenue / totalDiscount).toFixed(1) : 'N/A'
      };
  });

  return (
    <div className="space-y-[15px] max-w-7xl mx-auto animate-fade-in-up">
        {/* Header & Tabs */}
        <div className="flex flex-col md:flex-row justify-between items-end gap-[15px] border-b border-slate-200 pb-2">
            <div className="flex gap-[15px]">
                <button
                    onClick={() => setActiveTab('list')}
                    className={`pb-3 font-bold text-sm flex items-center gap-2 transition-all relative ${activeTab === 'list' ? 'text-indigo-600' : 'text-slate-500 hover:text-slate-700'}`}
                >
                    <Ticket size={18} /> {t.voucherMgmt}
                    {activeTab === 'list' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-indigo-600 rounded-t-full"></div>}
                </button>
                <button
                    onClick={() => setActiveTab('reports')}
                    className={`pb-3 font-bold text-sm flex items-center gap-2 transition-all relative ${activeTab === 'reports' ? 'text-indigo-600' : 'text-slate-500 hover:text-slate-700'}`}
                >
                    <BarChart2 size={18} /> {t.reports}
                    {activeTab === 'reports' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-indigo-600 rounded-t-full"></div>}
                </button>
            </div>
            <button
                onClick={() => { resetForm(); setIsModalOpen(true); }}
                className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-bold hover:bg-indigo-700 transition-colors flex items-center gap-2 shadow-lg shadow-indigo-200"
            >
                <Plus size={16} /> {t.addVoucher}
            </button>
        </div>

        {/* LIST VIEW */}
        {activeTab === 'list' && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[15px]">
                {state.vouchers.map(v => (
                    <div key={v.id} className="bg-white rounded-xl p-6 shadow-sm border border-slate-200 relative overflow-hidden hover:shadow-md transition-shadow">
                        {/* Status Strip */}
                        <div className={`absolute left-0 top-0 bottom-0 w-1 ${v.status === 'ACTIVE' ? 'bg-emerald-500' : 'bg-slate-300'}`}></div>

                        <div className="flex justify-between items-start mb-4">
                            <div>
                                <div className="flex items-center gap-2">
                                    <span className="font-mono text-lg font-bold text-slate-900 bg-slate-100 px-2 py-1 rounded border border-slate-200 border-dashed">{v.code}</span>
                                    {v.status === 'DISABLED' && <span className="text-[10px] font-bold bg-slate-200 text-slate-500 px-2 py-0.5 rounded-full">DISABLED</span>}
                                </div>
                                <p className="text-sm text-indigo-600 font-bold mt-1">
                                    {v.type === 'PERCENT' ? `${t.discountPercent} ${v.value}%` : `${t.discountFixed} ${formatCurrency(v.value)}`}
                                </p>
                            </div>
                            <div className="flex gap-1">
                                <button onClick={() => openEdit(v)} className="p-2 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"><Edit size={16}/></button>
                                <button onClick={() => setDeletingVoucherId(v.id)} className="p-2 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors"><Trash2 size={16}/></button>
                            </div>
                        </div>

                        <div className="space-y-2 text-sm text-slate-600 mb-4">
                            <div className="flex items-center gap-2">
                                <Tag size={14} className="text-slate-400"/>
                                <span>{t.voucherMinOrder}: {formatCurrency(v.minOrderValue)}</span>
                            </div>
                            <div className="flex items-center gap-2">
                                <Calendar size={14} className="text-slate-400"/>
                                <span>{new Date(v.startDate).toLocaleDateString()} - {new Date(v.endDate).toLocaleDateString()}</span>
                            </div>
                            <div className="flex items-center gap-2">
                                <TrendingUp size={14} className="text-slate-400"/>
                                <span>{t.voucherUsage}: <span className="font-bold text-slate-900">{v.usedCount}</span> / {v.usageLimit}</span>
                            </div>
                        </div>

                        {/* Progress Bar for Usage */}
                        <div className="w-full bg-slate-100 rounded-full h-1.5 mb-1">
                            <div className="bg-indigo-500 h-1.5 rounded-full transition-all duration-500" style={{width: `${Math.min(100, (v.usedCount/v.usageLimit)*100)}%`}}></div>
                        </div>
                    </div>
                ))}
            </div>
        )}

        {/* REPORTS VIEW */}
        {activeTab === 'reports' && (
            <div className="space-y-[15px]">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-[15px]">
                    {/* Chart */}
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
                        <h3 className="font-bold text-slate-800 mb-6">{t.performance}</h3>
                        <ResponsiveContainer width="100%" height={300}>
                            <BarChart data={voucherStats}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                <XAxis dataKey="code" tick={{fontSize: 10}} />
                                <YAxis yAxisId="left" orientation="left" stroke="#6366f1" />
                                <YAxis yAxisId="right" orientation="right" stroke="#f43f5e" />
                                <Tooltip formatter={(value: number) => formatCurrency(value)} />
                                <Legend />
                                <Bar yAxisId="left" dataKey="revenue" name={t.revenueGenerated} fill="#6366f1" radius={[4, 4, 0, 0]} />
                                <Bar yAxisId="right" dataKey="discount" name={t.totalDiscountGiven} fill="#f43f5e" radius={[4, 4, 0, 0]} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>

                    {/* Summary Table */}
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                        <h3 className="font-bold text-slate-800 mb-4">{t.detailedMetrics}</h3>
                        <div className="overflow-x-auto">
                            <table className="w-full text-left text-sm">
                                <thead className="bg-slate-50 text-slate-500 font-medium">
                                    <tr>
                                        <th className="px-4 py-3">{t.voucherCode}</th>
                                        <th className="px-4 py-3 text-center">{t.usageCount}</th>
                                        <th className="px-4 py-3 text-right">{t.totalDiscountGiven}</th>
                                        <th className="px-4 py-3 text-right">{t.revenueGenerated}</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-100">
                                    {voucherStats.map((stat, idx) => (
                                        <tr key={idx} className="hover:bg-slate-50">
                                            <td className="px-4 py-3 font-mono font-bold text-slate-700">{stat.code}</td>
                                            <td className="px-4 py-3 text-center">{stat.usage}</td>
                                            <td className="px-4 py-3 text-right text-rose-600 font-medium">{formatCurrency(stat.discount)}</td>
                                            <td className="px-4 py-3 text-right text-indigo-600 font-medium">{formatCurrency(stat.revenue)}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        )}

        {/* Modal */}
        {isModalOpen && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fade-in">
                <div className="absolute inset-0 bg-black/30" onClick={() => setIsModalOpen(false)}></div>
                <div className="bg-white rounded-xl w-full max-w-lg shadow-lg relative z-10 flex flex-col overflow-hidden">
                    <div className="px-6 py-4 border-b border-slate-100 bg-slate-50 flex justify-between items-center">
                        <h3 className="font-bold text-lg text-slate-900">{editingId ? t.editVoucher : t.addVoucher}</h3>
                        <button onClick={() => setIsModalOpen(false)}><X size={20} className="text-slate-400 hover:text-slate-600" /></button>
                    </div>
                    <form onSubmit={handleSubmit} className="p-6 space-y-[15px]">
                        <div className="grid grid-cols-2 gap-[15px]">
                            <div className="col-span-2">
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">{t.voucherCode}</label>
                                <input
                                    type="text" required
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none uppercase font-mono"
                                    value={formData.code}
                                    onChange={e => setFormData({...formData, code: e.target.value.toUpperCase()})}
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">{t.voucherType}</label>
                                <select
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm outline-none"
                                    value={formData.type}
                                    onChange={e => setFormData({...formData, type: e.target.value as any})}
                                >
                                    <option value="PERCENT">{t.percentOption}</option>
                                    <option value="FIXED">{t.fixedAmountOption}</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">{t.voucherValue}</label>
                                <input
                                    type={formData.type === 'PERCENT' ? 'number' : 'text'} required min="0"
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                                    value={formData.type === 'PERCENT' ? formData.value : (formData.value === 0 ? '' : new Intl.NumberFormat('vi-VN').format(formData.value).replace(/,/g, '.'))}
                                    onChange={e => {
                                        const val = e.target.value.replace(/\D/g, '');
                                        setFormData({...formData, value: parseFloat(val) || 0});
                                    }}
                                />
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-[15px]">
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">{t.voucherMinOrder}</label>
                                <input
                                    type="text" required
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                                    value={formData.minOrderValue === 0 ? '' : new Intl.NumberFormat('vi-VN').format(formData.minOrderValue).replace(/,/g, '.')}
                                    onChange={e => {
                                        const val = e.target.value.replace(/\D/g, '');
                                        setFormData({...formData, minOrderValue: parseFloat(val) || 0});
                                    }}
                                />
                            </div>
                            {formData.type === 'PERCENT' && (
                                <div>
                                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">{t.voucherMaxDiscount}</label>
                                    <input
                                        type="text"
                                        className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                                        value={formData.maxDiscount === 0 ? '' : new Intl.NumberFormat('vi-VN').format(formData.maxDiscount || 0).replace(/,/g, '.')}
                                        onChange={e => {
                                            const val = e.target.value.replace(/\D/g, '');
                                            setFormData({...formData, maxDiscount: parseFloat(val) || 0});
                                        }}
                                    />
                                </div>
                            )}
                        </div>

                        <div className="grid grid-cols-2 gap-[15px]">
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">Ngày bắt đầu</label>
                                <input
                                    type="date" required
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                                    value={formData.startDate}
                                    onChange={e => setFormData({...formData, startDate: e.target.value})}
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">Ngày kết thúc</label>
                                <input
                                    type="date" required
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                                    value={formData.endDate}
                                    onChange={e => setFormData({...formData, endDate: e.target.value})}
                                />
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-[15px]">
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">Giới hạn sử dụng</label>
                                <input
                                    type="text" required
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
                                    value={formData.usageLimit === 0 ? '' : new Intl.NumberFormat('vi-VN').format(formData.usageLimit).replace(/,/g, '.')}
                                    onChange={e => {
                                        const val = e.target.value.replace(/\D/g, '');
                                        setFormData({...formData, usageLimit: parseInt(val) || 1});
                                    }}
                                />
                            </div>
                            <div>
                                <label className="block text-xs font-bold text-slate-500 uppercase mb-1.5">{t.voucherStatus}</label>
                                <select
                                    className="w-full p-2.5 bg-white text-slate-900 border border-slate-200 rounded-xl text-sm outline-none"
                                    value={formData.status}
                                    onChange={e => setFormData({...formData, status: e.target.value as any})}
                                >
                                    <option value="ACTIVE">Active</option>
                                    <option value="DISABLED">Disabled</option>
                                </select>
                            </div>
                        </div>

                        <div className="pt-4 flex justify-end gap-3">
                            <button
                                type="button" onClick={() => setIsModalOpen(false)}
                                className="px-4 py-2 text-slate-500 hover:bg-slate-100 rounded-lg text-sm font-bold"
                            >
                                {t.cancel}
                            </button>
                            <button
                                type="submit"
                                className="px-6 py-2 bg-indigo-600 text-white hover:bg-indigo-700 rounded-lg text-sm font-bold shadow-md flex items-center gap-2"
                            >
                                <Save size={16} /> {t.save}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        )}

        <ConfirmModal
            isOpen={!!deletingVoucherId}
            onClose={() => setDeletingVoucherId(null)}
            onConfirm={() => {
                if (deletingVoucherId) {
                    deleteVoucher(deletingVoucherId);
                }
            }}
            title="Xác nhận xóa voucher"
            message="Bạn có chắc chắn muốn xóa mã voucher này?"
            lang={lang}
        />
    </div>
  );
};

export default VoucherManager;
